FROM billion-scale-benchmark

RUN apt-get update
RUN apt-get install -y wget git cmake g++ python3 python3-setuptools python3-pip
RUN pip3 install pybind11 numpy
RUN pip3 uninstall SimpleIndex
RUN git clone https://gitee.com/fissure/nipscompetition_test.git
RUN cd nipscompetition_test && python3 setup.py install
RUN python3 -c 'import SimpleIndex'
